export const MODAL_HOST_Z_INDEX = 1100;
export const MODAL_BACKDROP_COLOR = '#100C08';
export const MODAL_BACKDROP_TARGET_OPACITY = 0.28;
export const MODAL_BACKDROP_ENTER_DURATION_MS = 220;
export const MODAL_BACKDROP_EXIT_DURATION_MS = 180;
export const MODAL_DIALOG_MAX_WIDTH = 420;
export const MODAL_DIALOG_ENTER_DURATION_MS = 220;
export const MODAL_DIALOG_EXIT_DURATION_MS = 180;
export const MODAL_DIALOG_ENTER_SCALE = 0.96;
export const MODAL_DIALOG_TRANSLATE_Y = 12;
export const MODAL_SHEET_ENTER_DURATION_MS = 240;
export const MODAL_SHEET_EXIT_DURATION_MS = 200;
export const MODAL_SHEET_DISMISS_TRANSLATION_Y = 120;
export const MODAL_SHEET_DISMISS_VELOCITY_Y = 900;
export const MODAL_SHEET_HANDLE_WIDTH = 44;
export const MODAL_SHEET_HANDLE_HEIGHT = 5;
export const MODAL_SHEET_HANDLE_OPACITY = 0.2;
export const MODAL_STACK_BASE_Z_INDEX = 1;
export const MODAL_SHEET_SETTLE_SPRING = {
  damping: 22,
  stiffness: 240,
  mass: 0.9,
};
